name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  paths:
    description: 'Who to greet'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'