name: 'aws-ssm-parameters-action'
description: 'load ssm parameters from aws ssm'
author: 'Elias Júnior'
inputs:
  paths:
    required: true
  recursive:
    default: true
  with-decryption:
    default: false
  split-env:
    default: false
  upper-case:
    default: false
  env-prefix:
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
