name: 'aws-ssm-parameters-action'
description: 'load ssm parameters from aws ssm'
author: 'Elias Júnior'
inputs:
  paths:
    required: true
  recursive:
    default: true
  with-decryption:
    default: true
  region:
    default: 'us-east-1'
runs:
  using: 'node12'
  main: 'dist/index.js'