on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          paths: '/environments/production/projects/amigo-api/VAULT_PATH'